const authState={user:null,api:null,db:null};
const views=[...document.querySelectorAll('.view')];
function showView(name){views.forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===name&&x.closest('nav')));history.replaceState(null,'',name==='home'?'./':`#${name}`);scrollTo(0,0);if(name==='bellwork')openBellwork();if(name==='fast')openFast()}
document.querySelectorAll('[data-view]').forEach(x=>x.addEventListener('click',e=>{if(x.tagName==='BUTTON')e.preventDefault();showView(x.dataset.view)}));
const initial=location.hash.slice(1);showView(['bellwork','fast','explore'].includes(initial)?initial:'home');

// Each weekday keeps one skill all year; the prompt rotates weekly through
// four variants so students never see the same question two weeks in a row.
// Variant choice is derived from the date, so every student (and the teacher
// dashboard) sees the same prompt on the same day.
const dayPlans={
  1:{name:'Monday · Make a Claim',standard:'ELA.6.R.2.4',label:'Argument',goal:'2–3 complete sentences',variants:[
    ['Should sixth graders have a short independent reading time every school day? Make a claim and give one strong reason.','Sixth graders should/should not ___ because ___.'],
    ['Should phones stay in backpacks during class? Make a claim and support it with one strong reason.','Phones should/should not ___ because ___.'],
    ['Is it better to read the book or watch the movie version first? Make a claim and give one reason.','It is better to ___ first because ___.'],
    ['Should our class earn five extra minutes of free time if everyone finishes bell work all week? Make a claim and give one reason.','Our class should/should not ___ because ___.']
  ]},
  2:{name:'Tuesday · Read Between the Lines',standard:'ELA.6.R.1.1',label:'Inference',goal:'2–3 complete sentences',variants:[
    ['A character says, “It does not matter,” but folds the note carefully and places it in a desk drawer. What can you infer about the note? Use a detail from the sentence.','Readers can infer that ___ because the character ___.'],
    ['A student walks in smiling and holds a wrinkled test paper high in the air. What can you infer happened? Use one detail.','I can infer that ___ because ___.'],
    ['The dog sits by the front door with its leash in its mouth. What does the dog want? How do you know?','The dog wants ___ because ___.'],
    ['Maria checks the clock every minute and taps her foot. What can you infer about how she feels? Use one detail.','Maria probably feels ___ because ___.']
  ]},
  3:{name:'Wednesday · Word Detective',standard:'ELA.6.V.1.2',label:'Morphology & Context',goal:'2–3 complete sentences',variants:[
    ['In the sentence “The hikers were rejuvenated after resting beside the cool stream,” what does rejuvenated mean? What clue helped you decide?','Rejuvenated most likely means ___. The clue ___ helped me because ___.'],
    ['“The unbreakable mug fell off the table but did not crack.” What does unbreakable mean? Which word parts helped you figure it out?','Unbreakable means ___. The word parts ___ helped me because ___.'],
    ['“The crowd was so silent you could hear a pin drop.” What does “hear a pin drop” mean here? How do you know?','“Hear a pin drop” means ___ because ___.'],
    ['“She reread the confusing page slowly.” What does reread mean? How does the prefix re- help you know?','Reread means ___. The prefix re- means ___.']
  ]},
  4:{name:'Thursday · Explain the Evidence',standard:'ELA.6.R.2.2',label:'Central Idea',goal:'2–3 complete sentences',variants:[
    ['A community garden provides fresh food, gives neighbors a place to work together, and creates habitat for pollinators. What central idea connects these details?','The central idea is ___. The details show ___.'],
    ['School librarians repair old books, order new ones, and help students find stories they will love. What central idea connects these details?','The central idea is ___. The details show ___.'],
    ['Bees pollinate crops, make honey, and help flowers grow. What central idea do these details support?','The central idea is ___ because ___.'],
    ['A good teammate passes the ball, cheers for others, and practices hard. What central idea connects these details?','The central idea is ___. One detail that shows it is ___.']
  ]},
  5:{name:'Friday · Reflect & Revise',standard:'ELA.6.C.4.1',label:'Improving Writing',goal:'2–3 complete sentences',variants:[
    ['What reading or writing strategy helped you most this week? When did you use it, and why did it work?','The strategy that helped me most was ___. It worked when ___.'],
    ['What was the hardest thing you read or wrote this week? What made it hard, and what helped?','The hardest thing was ___. What helped me was ___.'],
    ['Pick one answer you wrote this week. How would you make it stronger if you wrote it again?','I would make it stronger by ___.'],
    ['What is one new word you learned this week? What does it mean, and where might you use it?','One word I learned is ___. It means ___.']
  ]}
};
let plan,todayKey,isWeekend;
const response=document.querySelector('#bell-response');
function dateKey(d=new Date()){return d.toLocaleDateString('en-CA')}
function planForToday(d=new Date()){const base=dayPlans[d.getDay()]||dayPlans[1],weekIndex=Math.floor(d.getTime()/6048e5);const[prompt,starter]=base.variants[weekIndex%base.variants.length];return{...base,prompt,starter}}
function refreshBellPlan(){
  const now=new Date();todayKey=dateKey(now);isWeekend=[0,6].includes(now.getDay());plan=planForToday(now);
  document.querySelector('#home-focus').textContent=isWeekend?'No bell work on weekends — a new prompt arrives Monday morning.':plan.prompt;
  document.querySelector('#bell-day-type').textContent=plan.name;document.querySelector('#bell-prompt').textContent=plan.prompt;document.querySelector('#bell-label').textContent=`${plan.standard} · ${plan.label}`;document.querySelector('#response-goal').textContent=plan.goal;document.querySelector('#sentence-starter').textContent=plan.starter;document.querySelector('#bell-date').textContent=now.toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'});
  const a=document.querySelector('#announcement');if(a){a.hidden=true;a.querySelector('span').textContent=''}
}
refreshBellPlan();
function draftKey(){return `bakerBellwork:${authState.user?.uid||'signed-out'}:${todayKey}`}
function stats(){const text=response.value.trim(),words=text?text.split(/\s+/).length:0,sentences=(text.match(/[.!?]+(?=\s|$)/g)||[]).length;document.querySelector('#word-count').textContent=words;document.querySelector('#sentence-count').textContent=sentences;return words}
response.addEventListener('input',()=>{localStorage.setItem(draftKey(),response.value);stats()});
document.querySelector('#starter-toggle').addEventListener('click',()=>document.querySelector('#sentence-starter').toggleAttribute('hidden'));
document.querySelector('#bellwork-signin').addEventListener('click',()=>document.querySelector('#account-dialog').showModal());
document.querySelector('#fast-signin').addEventListener('click',()=>document.querySelector('#account-dialog').showModal());
function updateGate(gateId,allowed,title,text){const gate=document.querySelector(gateId);gate.hidden=Boolean(allowed);if(allowed)return;gate.querySelector('h2').textContent=title;gate.querySelector('p').textContent=text;gate.querySelector('button').textContent='Sign in with your school account'}
let todaySubmission=null,editing=false;
function bellDocId(){return `${authState.user.uid}_${todayKey}`}
function setBellBadge(done){const card=document.querySelector('#bell-launch');if(card)card.classList.toggle('done',done);const tag=document.querySelector('#bell-launch-tag');if(tag)tag.textContent=done?'Completed today ✓':'Start here';const cta=document.querySelector('#bell-launch-cta');if(cta)cta.textContent=done?'Review →':'Open →';const note=document.querySelector('#home-note-btn');if(note)note.textContent=done?"Review today's bell work":'Begin bell work'}
async function openBellwork(){const signedIn=authState.user;updateGate('#bellwork-gate',signedIn,'Sign in before you begin','Bell work is connected to your account so Mrs. Baker can see who completed it and give useful feedback.');const weekendPanel=document.querySelector('#bellwork-weekend');if(!signedIn){document.querySelector('#bellwork-workspace').hidden=true;document.querySelector('#bellwork-done').hidden=true;weekendPanel.hidden=true;setBellBadge(false);return}if(isWeekend){weekendPanel.hidden=false;document.querySelector('#bellwork-workspace').hidden=true;document.querySelector('#bellwork-done').hidden=true;setBellBadge(false);loadHistory();return}weekendPanel.hidden=true;todaySubmission=null;try{const snap=await authState.api.getDoc(authState.api.doc(authState.db,'bellwork',bellDocId()));if(snap.exists())todaySubmission=snap.data()}catch(e){}renderBellState();loadHistory();setBellBadge(Boolean(todaySubmission))}
function renderBellState(){const showDone=Boolean(todaySubmission)&&!editing;document.querySelector('#bellwork-done').hidden=!showDone;document.querySelector('#bellwork-workspace').hidden=!authState.user||showDone;if(showDone){document.querySelector('#done-meta').textContent=`${todaySubmission.label||'Bell work'} · ${todaySubmission.wordCount||0} words · Confidence ${todaySubmission.confidence||'—'}/4${todaySubmission.editCount?' · Edited':''}`;document.querySelector('#done-response').textContent=todaySubmission.response||'';return}if(!authState.user)return;const editingExisting=editing&&todaySubmission;response.value=(editingExisting?todaySubmission.response:localStorage.getItem(draftKey()))||'';if(editingExisting){document.querySelector('#confidence').value=todaySubmission.confidence||'';['check-answer','check-evidence','check-revise'].forEach(id=>document.querySelector('#'+id).checked=true)}stats();document.querySelector('#submit-bellwork').textContent=editingExisting?'Update my answer':'Submit to Mrs. Baker';document.querySelector('#submission-message').textContent=''}
function openFast(){const allowed=authState.user;updateGate('#fast-gate',allowed,'Sign in to start the challenge','Your account keeps your personal best streak connected to you and updates the class Streak Spotlight automatically.');document.querySelector('#fast-game').hidden=!allowed;if(allowed)loadSkillStats()}

// Per-skill accuracy, persisted per student on this device.
let skillStats={};
function skillStoreKey(){return `bakerSkills:${authState.user?.uid||'anon'}`}
function loadSkillStats(){try{skillStats=JSON.parse(localStorage.getItem(skillStoreKey()))||{}}catch(e){skillStats={}}renderSkills()}
function renderSkills(){const el=document.querySelector('#skill-list');if(!el)return;const rows=Object.entries(skillStats).sort((a,b)=>b[1].t-a[1].t);el.innerHTML=rows.length?rows.map(([type,s])=>{const pct=s.t?Math.round(s.c/s.t*100):0;return `<li><span class="skill-name">${escapeHtml(type)}</span><span class="skill-meter"><span style="width:${pct}%"></span></span><b>${pct}%</b><small>${s.c}/${s.t}</small></li>`}).join(''):'<li class="skill-empty">Answer questions to see your skill levels grow.</li>'}
function recordSkill(type,correct){const s=skillStats[type]||{c:0,t:0};s.t++;if(correct)s.c++;skillStats[type]=s;try{localStorage.setItem(skillStoreKey(),JSON.stringify(skillStats))}catch(e){};if(authState.user&&authState.api&&authState.db)authState.api.setDoc(authState.api.doc(authState.db,'users',authState.user.uid),{skills:skillStats,updatedAt:authState.api.serverTimestamp()},{merge:true}).catch(()=>{});renderSkills()}

// Consecutive school-day bell work streak, computed from submission history.
function bellStreakFrom(items){const have=new Set(items.map(x=>x.date));const key=d=>d.toLocaleDateString('en-CA');const prevSchool=d=>{do{d.setDate(d.getDate()-1)}while([0,6].includes(d.getDay()));return d};let d=new Date();if([0,6].includes(d.getDay())||!have.has(key(d)))d=prevSchool(new Date());let n=0;while(have.has(key(d))){n++;d=prevSchool(d)}return n}
const MIN_WORDS=8;
document.querySelector('#submit-bellwork').addEventListener('click',async()=>{const message=document.querySelector('#submission-message');const words=stats(),checksDone=['check-answer','check-evidence','check-revise'].every(id=>document.querySelector(`#${id}`).checked),need=[];if(words<MIN_WORDS)need.push(`write a little more (you have ${words} of ${MIN_WORDS}+ words)`);if(!checksDone)need.push('check the three boxes');if(!document.querySelector('#confidence').value)need.push('choose a confidence level');if(need.length){message.textContent='Almost there — just '+need.join(', and ')+'.';return}message.textContent='Submitting...';const ref=authState.api.doc(authState.db,'bellwork',bellDocId()),isEdit=Boolean(todaySubmission),data={studentUid:authState.user.uid,studentName:authState.user.displayName||'Student',period:authState.period||null,date:todayKey,standard:plan.standard,label:plan.label,prompt:plan.prompt,response:response.value.trim(),wordCount:words,confidence:Number(document.querySelector('#confidence').value),status:'submitted',submittedAt:isEdit?(todaySubmission.submittedAt||authState.api.serverTimestamp()):authState.api.serverTimestamp()};if(isEdit){data.editedAt=authState.api.serverTimestamp();data.editCount=(todaySubmission.editCount||0)+1}try{await authState.api.setDoc(ref,data);try{const snap=await authState.api.getDoc(ref);todaySubmission=snap.exists()?snap.data():data}catch(e){todaySubmission=data}editing=false;localStorage.removeItem(draftKey());renderBellState();await loadHistory();setBellBadge(true);scrollTo(0,0)}catch(e){message.textContent='Submission did not save. Your draft is still safe on this device.'}});
document.querySelector('#done-edit').addEventListener('click',()=>{editing=true;renderBellState();scrollTo(0,0)});
async function loadHistory(){if(!authState.user||!authState.api)return;let items=[];try{const q=authState.api.query(authState.api.collection(authState.db,'bellwork'),authState.api.where('studentUid','==',authState.user.uid)),snap=await authState.api.getDocs(q);items=snap.docs.map(d=>d.data()).sort((a,b)=>(b.date||'').localeCompare(a.date||'')).slice(0,10)}catch(e){}const html=items.length?items.map(x=>`<article><b>${escapeHtml(x.date)} · ${escapeHtml(x.label)}</b><p>${escapeHtml(x.response)}</p><small>${x.wordCount||0} words · Confidence ${x.confidence||'—'}/4</small></article>`).join(''):'<p>No bell work submitted yet.</p>';document.querySelectorAll('.bell-history-list').forEach(el=>el.innerHTML=html);document.querySelectorAll('.bell-history-count').forEach(el=>el.textContent=items.length);const streakEl=document.querySelector('#done-streak'),n=bellStreakFrom(items);streakEl.hidden=n<2;if(n>=2)streakEl.textContent=`🔥 ${n}${items.length>=10&&n>=10?'+':''}-day bell work streak — keep it going!`}
function escapeHtml(v){const d=document.createElement('div');d.textContent=String(v||'');return d.innerHTML}
// Teacher-published overrides for today (settings/today): replacement prompt
// and/or a class announcement. Public read; written from the teacher dashboard.
let settingsLoaded=false;
async function applyTodaySettings(){
  if(settingsLoaded||!authState.api||!authState.db)return;settingsLoaded=true;
  try{
    const snap=await authState.api.getDoc(authState.api.doc(authState.db,'settings','today'));
    if(!snap.exists())return;const s=snap.data();
    if(s.date!==todayKey)return;
    if(s.prompt){plan.prompt=s.prompt;if(s.starter)plan.starter=s.starter;
      document.querySelector('#bell-prompt').textContent=plan.prompt;
      document.querySelector('#sentence-starter').textContent=plan.starter;
      if(!isWeekend)document.querySelector('#home-focus').textContent=plan.prompt}
    if(s.announcement){const a=document.querySelector('#announcement');a.hidden=false;a.querySelector('span').textContent=s.announcement}
  }catch(e){}
}
window.addEventListener('baker-auth-change',({detail})=>{Object.assign(authState,detail);if(authState.user){const oldKey=`bakerBellwork:signed-out:${todayKey}`,newKey=draftKey(),draft=localStorage.getItem(oldKey);if(draft&&!localStorage.getItem(newKey)){localStorage.setItem(newKey,draft);localStorage.removeItem(oldKey)}}applyTodaySettings();openBellwork();openFast();loadLeaderboard()});

document.addEventListener('visibilitychange',()=>{if(document.visibilityState!=='visible'||dateKey()===todayKey)return;refreshBellPlan();todaySubmission=null;editing=false;settingsLoaded=false;applyTodaySettings();openBellwork();setBellBadge(false)});

function leaderboardName(name){const normal=authState.api?.normalizeName?authState.api.normalizeName(name):String(name||'Student').trim();const parts=normal.split(/\s+/).filter(Boolean);return parts.length>1?`${parts[0]} ${parts.at(-1)[0]}.`:parts[0]||'Student'}
async function loadLeaderboard(){if(!authState.api||!authState.db)return;try{const q=authState.api.query(authState.api.collection(authState.db,'leaderboard'),authState.api.orderBy('bestStreak','desc'),authState.api.limit(10)),snap=await authState.api.getDocs(q),items=snap.docs.map(d=>d.data());document.querySelector('#leaderboard-list').innerHTML=items.length?items.map((x,i)=>`<li data-rank="${i+1}"><b>${escapeHtml(x.displayName)}</b><span>${x.period?`Period ${escapeHtml(x.period)}`:'Mrs. Baker’s ELA'}</span><b>${x.bestStreak} in a row</b></li>`).join(''):'<li class="leaderboard-empty">Be the first student to set a class streak.</li>'}catch(e){document.querySelector('#leaderboard-list').innerHTML='<li class="leaderboard-empty">The leaderboard will appear after students begin practicing.</li>'}}
async function saveBestStreak(){if(!authState.user||!authState.api||streak<2)return;try{const ref=authState.api.doc(authState.db,'leaderboard',authState.user.uid),current=await authState.api.getDoc(ref),best=current.data()?.bestStreak||0;if(streak>best){await authState.api.setDoc(ref,{uid:authState.user.uid,displayName:leaderboardName(authState.user.displayName),period:authState.period||null,bestStreak:streak,updatedAt:authState.api.serverTimestamp()},{merge:true});loadLeaderboard()}}catch(e){}}

const passages=[
 {type:'Informational',standard:'ELA.6.R.2.2',text:'Each spring, horseshoe crabs crawl onto beaches to lay eggs. Migrating shorebirds arrive at nearly the same time and depend on those eggs for energy during their long journeys. When horseshoe crab numbers fall, some bird populations struggle too.',qs:[['Which central idea is best supported?',['Horseshoe crabs and shorebirds are connected in an important food relationship.','All shorebirds live only on beaches.','Horseshoe crabs migrate farther than birds.','Spring weather makes animals struggle.'],0,'The passage connects horseshoe crab eggs directly to the survival of migrating shorebirds.'],['Why does the author mention when the birds arrive?',['To explain why beaches are warm','To show that timing makes the eggs an important food source','To prove birds lay eggs in spring','To compare two migration distances'],1,'The matching timing explains why the crabs’ eggs matter to the birds.'],['What can be inferred if crab numbers recover?',['Some shorebirds may have more food during migration.','All beach animals will leave.','The birds will stop migrating.','Spring will begin earlier.'],0,'More crabs can mean more eggs, which the passage identifies as migration fuel.'],['Which detail best develops the central idea?',['Each spring','crawl onto beaches','shorebirds depend on those eggs for energy','during their long journeys'],2,'That detail explicitly shows the relationship between the two animals.']]},
 {type:'Literary',standard:'ELA.6.R.1.1',text:'Maya stood behind the curtain, turning her note cards over and over. When her name was announced, she tucked the cards into her pocket, stepped toward the microphone, and began the speech from memory. Her first sentence trembled, but the second rang clearly across the room.',qs:[['How does Maya change?',['She becomes less prepared.','She moves from nervousness toward confidence.','She decides not to speak.','She becomes angry with the audience.'],1,'Her trembling start followed by a clear sentence shows growing confidence.'],['Which detail best shows Maya is nervous?',['Her name was announced.','She stood behind a curtain.','She turned her note cards over and over.','She spoke from memory.'],2,'The repeated motion is a physical clue to her nervousness.'],['Why does Maya put away the cards?',['She forgot how to read.','She wants to challenge herself to speak from memory.','The cards are incorrect.','The audience cannot see them.'],1,'Her next action, beginning from memory, supports this inference.'],['What theme is beginning to develop?',['Preparation can help someone act despite fear.','Speaking is always easy.','Audiences dislike note cards.','Memories are unreliable.'],0,'Maya is prepared, still afraid, and chooses to act anyway.']]},
 {type:'Informational',standard:'ELA.6.R.2.1',text:'A city library created a “library of things” beside its shelves of books. Residents can borrow tools, sewing machines, board games, and baking pans. The program saves families money and reduces waste because many people share items that would otherwise be purchased and rarely used.',qs:[['How is the passage mainly organized?',['Chronological order','Cause and effect','Problem and solution','Compare and contrast'],2,'The program is presented as a solution that saves money and reduces waste.'],['What is the main purpose of the examples?',['To show the variety of useful items people can borrow','To explain how books are printed','To prove board games are expensive','To list items the library sells'],0,'The list illustrates what “things” means in this unusual library.'],['Which is the best summary?',['Libraries should stop lending books.','A library lends shared household items, helping residents save money and reduce waste.','Baking pans are the most popular library items.','Families rarely use tools.'],1,'It includes the program and both important benefits without minor details.'],['What does otherwise mean here?',['In a different situation','Very quickly','At the library','Without payment'],0,'The sentence means the items would be bought in a different situation.']]},
 {type:'Literary',standard:'ELA.6.R.1.2',text:'Leo planted three sunflower seeds in a chipped blue pot. For weeks, nothing appeared. His brother told him to throw the soil away, but Leo kept watering it each morning. One rainy Tuesday, a green hook finally pushed through the dirt.',qs:[['Which theme is best supported?',['Patience and steady effort can lead to results.','Rain ruins careful plans.','Brothers always disagree.','Old pots cannot grow plants.'],0,'Leo continues caring for the seeds despite seeing no immediate result.'],['Which detail most clearly develops the theme?',['The pot is blue.','Leo keeps watering even when nothing appears.','Tuesday is rainy.','There are three seeds.'],1,'His repeated effort is the key evidence for perseverance.'],['What does the green hook refer to?',['A garden tool','A new plant sprout','A piece of the pot','A worm'],1,'Its movement through the dirt after watering identifies it as a sprout.'],['How does the brother affect the plot?',['He waters the plant.','His doubt creates a choice for Leo to quit or continue.','He breaks the pot.','He plants another seed.'],1,'The brother’s advice creates a moment when Leo must choose persistence.']]},
 {type:'Informational',standard:'ELA.6.R.2.3',text:'One article argues that school gardens improve science learning because students observe ecosystems directly. Another article supports gardens because growing vegetables can expand access to fresh food. Both authors favor gardens, but they emphasize different benefits.',qs:[['How do the authors’ purposes differ?',['One emphasizes learning; the other emphasizes food access.','One opposes gardens; the other supports them.','Both focus only on cost.','Both explain how to plant seeds.'],0,'The passage directly names the different benefits each author emphasizes.'],['What do both authors agree about?',['Gardens are difficult to maintain.','Schools should have gardens.','Science is the only useful subject.','Vegetables should be free.'],1,'The final sentence states that both favor gardens.'],['Which text structure dominates?',['Sequence','Cause and effect','Compare and contrast','Description'],2,'The passage identifies a similarity and a difference between two articles.'],['What does emphasize mean?',['To give special importance to','To disagree loudly','To remove evidence','To repeat word for word'],0,'Each author gives special importance to a different benefit.']]},
 {type:'Literary',standard:'ELA.6.R.1.3',text:'I insisted the shortcut through the field would save us ten minutes. Halfway across, mud swallowed my left shoe. My cousin stood on the dry sidewalk, trying not to laugh. “Excellent navigation,” she called while I hopped back for the shoe.',qs:[['How does first-person point of view affect the passage?',['It lets readers experience the narrator’s mistaken confidence directly.','It reveals every character’s private thoughts.','It makes the passage a news report.','It prevents humor.'],0,'The narrator admits the poor decision and describes the embarrassing result firsthand.'],['The cousin’s words are an example of—',['a sincere compliment','verbal irony','a scientific claim','a flashback'],1,'She says the opposite of what she means after the shortcut fails.'],['What tone does the passage create?',['Threatening','Humorous','Formal','Mysterious'],1,'The lost shoe, hopping, and ironic comment make the event playful.'],['Which detail best reveals the narrator’s original attitude?',['mud swallowed my shoe','I insisted the shortcut would save time','my cousin stood on the sidewalk','I hopped back'],1,'“Insisted” shows strong confidence before the plan fails.']]},
 {type:'Vocabulary',standard:'ELA.6.V.1.2',text:'After weeks without rain, the brittle grass crunched under every step. Gardeners conserved water by collecting the small amount that dripped from air conditioners and using it on their most delicate plants.',qs:[['What does conserved mean?',['Used carelessly','Saved and used carefully','Heated quickly','Poured away'],1,'The gardeners collect limited water and direct it where it is most needed.'],['Which context clue best supports the meaning of brittle?',['weeks without rain','gardeners conserved','air conditioners','delicate plants'],0,'A long dry period explains why the grass is dry enough to break or crunch.'],['Which word is closest in meaning to delicate?',['Fragile','Enormous','Common','Artificial'],0,'Delicate plants are easily harmed and need careful treatment.'],['How does the suffix -ed function in conserved?',['It shows a past action.','It means without.','It changes the word into a person.','It means again.'],0,'The suffix marks the verb as happening in the past.']]},
 {type:'Argument',standard:'ELA.6.R.2.4',text:'The student council proposes adding refill stations for water bottles. The group argues that stations would reduce plastic waste and make drinking water easier to access. Their survey found that 68 percent of students already carry reusable bottles at least twice a week.',qs:[['Which evidence most directly supports easier access?',['Plastic can become waste.','Many students already carry reusable bottles.','The student council meets weekly.','Surveys use percentages.'],1,'Students who already carry bottles could readily use refill stations.'],['What is the council’s main claim?',['Schools should sell more plastic bottles.','Adding refill stations would benefit the school.','Students dislike drinking water.','Surveys should happen twice a week.'],1,'The reasons about waste and access support installing the stations.'],['Which additional evidence would best strengthen the argument?',['The color of current fountains','The cost and expected use of refill stations','A list of council members','The history of plastic'],1,'Cost and expected use would help evaluate whether the proposal is practical and useful.'],['Why is the survey relevant?',['It shows many potential users already have reusable bottles.','It proves all students agree.','It explains how plastic is made.','It compares two schools.'],0,'The survey establishes a likely group of students who would use the stations.']]},
 {type:'Poetry',standard:'ELA.6.R.1.4',text:'The morning folds its silver map,\nacross the waking bay;\none bright path trembles on the waves,\nthen slowly points the way.',qs:[['What is being personified?',['Morning','A map','A path','The waves'],0,'Morning is given the humanlike ability to fold and present a map.'],['What does the silver map most likely represent?',['A paper map','Sunlight spreading over the water','A fishing net','Clouds covering the bay'],1,'The bright path across waking water suggests reflected morning light.'],['How does the four-line form affect the poem?',['It presents one focused image in a brief moment.','It explains a long historical event.','It creates a debate between speakers.','It gives detailed instructions.'],0,'The compact stanza concentrates attention on a single sunrise image.'],['Which mood is created?',['Peaceful and hopeful','Angry and loud','Confused and frantic','Gloomy and hopeless'],0,'Words such as waking, bright, and points the way create calm hopefulness.']]},
 {type:'Informational',standard:'ELA.6.R.2.2',text:'Mangrove roots form tangled walls along Florida shorelines. The roots slow waves, trap sediment, and provide hiding places for young fish. During storms, mangrove forests can also reduce some of the energy that reaches coastal communities.',qs:[['Which is the best central idea?',['Mangroves protect and support coastal environments in several ways.','All fish live in mangrove roots.','Storms only happen near forests.','Sediment damages every shoreline.'],0,'The passage lists multiple ecological and protective benefits.'],['Which detail shows a benefit to animals?',['The roots slow waves.','The roots trap sediment.','The roots provide hiding places for young fish.','Forests reduce energy.'],2,'The hiding places directly support young fish.'],['What relationship does the passage show?',['Mangrove features cause several shoreline benefits.','Fish cause storms.','Sediment removes roots.','Communities plant waves.'],0,'The physical roots lead to reduced waves, trapped sediment, and habitat.'],['What does coastal mean?',['Related to land near the sea','Located underground','Far from water','Made by young fish'],0,'Shorelines, waves, and storms provide context for land near the sea.']]},
 {type:'Literary',standard:'ELA.6.R.1.1',text:'Nia had practiced the piano piece until her family could hum every measure. At the recital, the bench felt too high and the lights too bright. She missed one note, paused, and heard her teacher whisper, “Keep going.” Nia took a breath and found the next measure.',qs:[['Which event is the turning point?',['Her family learns the tune.','The bench feels high.','She hears “Keep going” and resumes playing.','The lights are bright.'],2,'The encouragement changes her from pausing after a mistake to continuing.'],['What conflict does Nia face?',['Person versus nature','Person versus self','Person versus society','Person versus technology'],1,'She must manage her own fear and response to making a mistake.'],['Which theme is supported?',['A mistake does not have to end an effort.','Practice guarantees perfection.','Bright lights improve music.','Teachers should perform for students.'],0,'Nia makes a mistake, recovers, and continues.'],['How does the setting influence Nia?',['The recital environment increases her nervousness.','The piano is outdoors.','Her family leaves the room.','The bench makes the music easier.'],0,'The unfamiliar bench and bright stage lights contribute to her discomfort.']]},
 {type:'Argument',standard:'ELA.6.R.2.4',text:'A writer claims that students should help choose some library purchases. She explains that students are more likely to read books connected to their interests. She also notes that librarians would still review every suggestion for age appropriateness and quality.',qs:[['Which sentence states the claim?',['Students should help choose some library purchases.','Students have many interests.','Librarians read books.','Every suggestion has a title.'],0,'That statement is the position the remaining reasons support.'],['Why does the writer mention librarian review?',['To address a concern about unsuitable choices','To prove students cannot read','To explain library hours','To criticize book quality'],0,'The detail answers a likely concern while preserving professional review.'],['Which is a reason supporting the claim?',['Libraries contain shelves.','Students may read more when books match their interests.','All books are the same quality.','Suggestions must be handwritten.'],1,'Greater interest and reading is the stated benefit.'],['What counterclaim is the writer most likely responding to?',['Students may suggest books that are not appropriate or useful.','Libraries have no books.','Students dislike having choices.','Librarians never review purchases.'],0,'The assurance that librarians review suggestions directly addresses that concern.']]},
 {type:'Informational',standard:'ELA.6.R.2.1',text:'At first, scientists counted manatees from boats and airplanes. Today, some researchers also use drones to photograph shallow water from above. Computer programs help compare the images, but trained scientists still review the results because glare, waves, and shadows can be mistaken for animals.',qs:[['How does the passage develop information?',['It contrasts an earlier method with newer tools.','It lists events in a manatee’s life.','It argues that airplanes should be banned.','It describes only computer software.'],0,'The passage moves from earlier counting methods to current drone and computer support.'],['Why must scientists still review the images?',['Drones cannot take photographs.','Conditions in the water can create misleading shapes.','Manatees always hide under boats.','Computer programs count only shadows.'],1,'The final clause names glare, waves, and shadows as possible sources of mistakes.'],['Which is the best summary?',['Technology helps researchers count manatees, but human review remains important.','Scientists no longer use boats.','Shallow water contains no glare.','Airplanes are more accurate than every other tool.'],0,'It captures both the benefit of technology and the need for expert checking.'],['What does trained imply about the scientists?',['They have practiced and developed specialized knowledge.','They travel only by train.','They are new to the work.','They avoid using evidence.'],0,'Reviewing difficult images accurately requires learned expertise.']]},
 {type:'Informational',standard:'ELA.6.R.2.3',text:'Newly hatched sea turtles find the ocean by crawling toward the brightest part of the horizon. On developed beaches, porch lights and streetlamps can pull hatchlings inland instead, where they are in danger. Many Florida beach towns now ask residents to shield their lights or switch to amber bulbs during nesting season.',qs:[['What problem does the passage describe?',['Sea turtles dislike swimming at night.','Artificial lights can draw hatchlings away from the ocean.','Beach towns have too few streetlamps.','Amber bulbs are hard to find.'],1,'The second sentence explains that lights pull hatchlings inland, into danger.'],['What solution do beach towns suggest?',['Moving nests closer to houses','Banning beach visits','Shielding lights or using amber bulbs in nesting season','Raising hatchlings indoors'],2,'The final sentence names both light fixes during nesting season.'],['Why do hatchlings crawl toward lights?',['They mistake them for the bright ocean horizon.','They are looking for food.','They follow older turtles.','They avoid the dark sand.'],0,'The first sentence says hatchlings head for the brightest horizon, which lights imitate.'],['What does developed mean in “developed beaches”?',['Empty and wild','Underwater','Photographed often','Built up with buildings and roads'],3,'Porch lights and streetlamps signal a beach with construction around it.']]},
 {type:'Literary',standard:'ELA.6.R.1.1',text:'Jaden counted his lawn-mowing money twice, then slid the envelope across the table to his little brother. “The bike shop closes at six,” he said, pulling on his shoes. “If we hurry, you can ride it home tonight.”',qs:[['What can you infer Jaden is doing?',['Paying back money he borrowed','Using his earnings to buy his brother a bike','Hiding his money from his brother','Asking his brother to mow lawns'],1,'He gives his earned money to his brother and mentions reaching the bike shop in time.'],['Which detail best shows the money is Jaden’s own?',['The envelope is on the table.','The shop closes at six.','He counted his lawn-mowing money.','He pulls on his shoes.'],2,'“Lawn-mowing money” shows he earned it himself.'],['What theme is this moment developing?',['Generosity can mean giving up something you worked for.','Bikes are faster than walking.','Money should be counted twice.','Stores should stay open later.'],0,'Jaden hands over money he earned so his brother can have the bike.'],['Why does the author include “counted his money twice”?',['To show Jaden is bad at math','To show the bike shop is expensive','To show Jaden cannot decide','To show the amount matters to him before he gives it away'],3,'Careful counting shows the money is meaningful, which makes the gift bigger.']]},
 {type:'Vocabulary',standard:'ELA.6.V.1.2',text:'Mia was reluctant to try the climbing wall. She watched three friends go first, checked her harness twice, and finally placed one careful hand on the lowest hold.',qs:[['What does reluctant mean?',['Excited and eager','Slow to agree or hesitant','Angry and loud','Skilled and confident'],1,'Her watching, double-checking, and waiting show she is hesitant.'],['Which detail is the best clue to the meaning of reluctant?',['The wall has a lowest hold.','Three friends are present.','She watched others go first and checked her harness twice.','The harness is safe.'],2,'Delaying and double-checking signal hesitation.'],['What does the word finally suggest?',['She quit climbing.','The wall was closed.','Her friends gave up waiting.','Some time passed before she acted.'],3,'“Finally” marks the end of her long hesitation.'],['Which word is closest in meaning to reluctant?',['Unwilling','Cheerful','Fearless','Prepared'],0,'Reluctant describes someone who holds back or is unwilling at first.']]},
 {type:'Informational',standard:'ELA.6.R.2.2',text:'Last year, students in the recycling club weighed every classroom bin before pickup. Paper made up nearly half of the school’s waste, so the club placed a recycling box in each room and added morning announcements about reusing paper. By spring, the school’s trash weight had dropped by one fifth.',qs:[['Which central idea is best supported?',['Morning announcements are entertaining.','Schools produce no waste in spring.','Student-led measuring and small changes reduced the school’s waste.','Paper should be banned from classrooms.'],2,'The passage moves from measuring the problem to actions to a measurable result.'],['Why did the club focus on paper?',['Their measurements showed paper was nearly half the waste.','Paper is easy to carry.','The principal asked them to.','Other materials cannot be recycled.'],0,'The weighing data pointed at paper as the biggest target.'],['What does the final sentence add to the passage?',['A new problem to solve','An opinion about recycling','A description of the bins','Evidence that the plan worked'],3,'The one-fifth drop in trash weight shows the actions had an effect.'],['Which text structure best describes this passage?',['Compare and contrast','Problem and solution','Chronological biography','Question and answer'],1,'A waste problem is identified, addressed, and resolved with results.']]},
 {type:'Poetry',standard:'ELA.6.R.1.4',text:'The library in the morning is a harbor—\nquiet boats of books at rest,\neach spine a mast, each page a sail\nwaiting for the wind of a reader’s breath.',qs:[['What is the library compared to?',['A classroom','A storm','A harbor','A forest'],2,'The first line makes the comparison directly: the library “is a harbor.”'],['In this metaphor, what are the books?',['Boats at rest','Waves','The wind','Sailors'],0,'Line two calls them “quiet boats of books.”'],['What does “the wind of a reader’s breath” suggest?',['Reading aloud is too noisy.','The library is cold.','Wind damages books.','A reader brings the books to life and sets them moving.'],3,'Sails wait for wind; books wait for readers to make them “go.”'],['Which mood does the poem create?',['Frantic and rushed','Calm and inviting','Gloomy and lonely','Angry and tense'],1,'Words like quiet, at rest, and waiting build a peaceful, welcoming feeling.']]}
];
function shuffle(a){const copy=[...a];for(let i=copy.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[copy[i],copy[j]]=[copy[j],copy[i]]}return copy}
function buildFastOrder(){return shuffle(passages.map((p,pi)=>({p,pi}))).flatMap(({p,pi})=>p.qs.map((q,qi)=>({id:`${pi}-${qi}`,type:p.type,standard:p.standard,passage:p.text,question:q[0],answers:q[1],correct:q[2],explanation:q[3]})))}
let fastOrder=[],fastIndex=0,answered=0,score=0,streak=0;
function resetFast(){fastOrder=buildFastOrder();fastIndex=score=streak=answered=0;renderQuestion();updateGame()}
function renderQuestion(){if(fastIndex>=fastOrder.length){fastOrder=buildFastOrder();fastIndex=0}const q=fastOrder[fastIndex];document.querySelector('#fast-category').textContent=q.type;document.querySelector('#fast-standard').textContent=q.standard;document.querySelector('#fast-passage').innerHTML=escapeHtml(q.passage).replaceAll('\n','<br>');document.querySelector('#fast-question').textContent=q.question;document.querySelector('#fast-answers').innerHTML=q.answers.map((a,i)=>`<button data-answer="${i}"><b>${String.fromCharCode(65+i)}</b> ${escapeHtml(a)}</button>`).join('');document.querySelector('#fast-feedback').textContent='Choose the answer that the text supports best.';document.querySelector('#fast-next').hidden=true;document.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>answerQuestion(Number(b.dataset.answer))))}
function answerQuestion(choice){const q=fastOrder[fastIndex],correct=choice===q.correct;document.querySelectorAll('[data-answer]').forEach((b,i)=>{b.disabled=true;if(i===q.correct)b.classList.add('correct');else if(i===choice)b.classList.add('incorrect')});answered++;if(correct){score+=10+Math.min(streak,5)*2;streak++;saveBestStreak()}else streak=0;recordSkill(q.type,correct);document.querySelector('#fast-feedback').innerHTML=`<b>${correct?'Correct!':'Not quite.'}</b> ${escapeHtml(q.explanation)}`;document.querySelector('#fast-next').hidden=false;updateGame()}
function updateGame(){document.querySelector('#fast-score').textContent=score;document.querySelector('#fast-streak').textContent=streak;document.querySelector('#fast-count').textContent=answered;const best=Object.entries(skillStats).filter(([,s])=>s.t).sort((a,b)=>(b[1].c/b[1].t)-(a[1].c/a[1].t)||b[1].t-a[1].t)[0];document.querySelector('#fast-best').textContent=best?best[0]:'Start playing'}
document.querySelector('#fast-next').addEventListener('click',()=>{fastIndex++;renderQuestion();updateGame()});document.querySelector('#fast-reset').addEventListener('click',resetFast);resetFast();
document.querySelectorAll('[data-panel]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-panel]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.explore-panel').forEach(x=>x.classList.toggle('active',x.id===`panel-${b.dataset.panel}`));if(b.dataset.panel==='data')setTimeout(revealAnalytics,60)}));

// ---- Public Grade 6 FAST analytics (Explore → Public Data) ----
// Source: Florida DOE 2025 Statewide Assessment Results, Grade 6 ELA. Edit these
// numbers to update the charts. Percentages are rounded and may not total 100.
const fastData={
  tested:3861,
  proficiency:[{label:'Florida',pct:60},{label:'Manatee County',pct:53}],
  levels:[
    {n:1,name:'Needs substantial support',pct:24,passing:false,blurb:'Reading skills are still developing and need the most support. With focused daily practice, this is the group that can show the biggest growth across a school year.'},
    {n:2,name:'Approaching grade level',pct:23,passing:false,blurb:'Close to grade level. A consistent year of reading-strategy practice moves many of these students up to Level 3.'},
    {n:3,name:'On grade level',pct:22,passing:true,blurb:'The FAST “passing” line. Students show a satisfactory understanding of Grade 6 reading skills.'},
    {n:4,name:'Proficient',pct:20,passing:true,blurb:'Students apply Grade 6 reading skills confidently across different kinds of texts.'},
    {n:5,name:'Mastery',pct:12,passing:true,blurb:'Students handle complex texts and tricky questions with consistent accuracy.'}
  ]
};
const levelColors=['#f7d7e3','#f0a9c4','#d94f82','#a43863','#742747'];
function selectLevel(i){const l=fastData.levels[i];document.querySelectorAll('.level-seg,.legend-row').forEach(b=>b.classList.toggle('selected',Number(b.dataset.level)===i));const d=document.querySelector('#level-detail');d.style.borderLeftColor=levelColors[i];d.innerHTML=`<b style="color:${levelColors[i]}">Level ${l.n} · ${escapeHtml(l.name)}</b> — ${escapeHtml(l.blurb)}<em>${l.passing?'Counts as reading on grade level (Level 3 and above).':'Below the Grade 6 grade-level line — a focus area for growth.'}</em>`}
function revealAnalytics(){document.querySelectorAll('.prof-fill').forEach(f=>{f.style.width=f.dataset.pct+'%'});document.querySelectorAll('.level-seg').forEach((s,i)=>{s.style.flexGrow=fastData.levels[i].pct})}
function buildAnalytics(){
  const profEl=document.querySelector('#prof-bars');if(!profEl)return;
  profEl.innerHTML=fastData.proficiency.map(p=>`<div class="prof-row"><span class="prof-label">${p.label}</span><div class="prof-track"><div class="prof-fill" data-pct="${p.pct}" style="width:0"><b>${p.pct}%</b></div></div></div>`).join('');
  document.querySelector('#level-bar').innerHTML=fastData.levels.map((l,i)=>`<button class="level-seg" data-level="${i}" style="flex-grow:0;flex-basis:0;background:${levelColors[i]};color:${i>=2?'#fff':'var(--deep)'}" aria-label="Level ${l.n}, ${l.pct} percent"><b>${l.pct}%</b><small>L${l.n}</small></button>`).join('');
  document.querySelector('#level-legend').innerHTML=fastData.levels.map((l,i)=>`<li><button class="legend-row" data-level="${i}"><span class="dot" style="background:${levelColors[i]}"></span><b>Level ${l.n}</b><span class="legend-name">${escapeHtml(l.name)}</span><b class="legend-pct">${l.pct}%</b></button></li>`).join('');
  document.querySelectorAll('.level-seg,.legend-row').forEach(b=>b.addEventListener('click',()=>selectLevel(Number(b.dataset.level))));
  document.querySelector('#data-source').innerHTML=`Source: Florida Department of Education, 2025 Statewide Assessment Results (Grade 6 ELA). Manatee County students tested: ${fastData.tested.toLocaleString()}. Percentages are rounded and may not total 100. Shown for context only — please verify against the official district report before sharing widely. Updated June 2026.`;
}
buildAnalytics();
