const authState={user:null,classCode:'',api:null,db:null};
const views=[...document.querySelectorAll('.view')];
function showView(name){views.forEach(v=>v.classList.toggle('active',v.id===`view-${name}`));document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x.dataset.view===name&&x.closest('nav')));history.replaceState(null,'',name==='home'?'index.html':`#${name}`);scrollTo(0,0);if(name==='bellwork')openBellwork()}
document.querySelectorAll('[data-view]').forEach(x=>x.addEventListener('click',e=>{if(x.tagName==='BUTTON')e.preventDefault();showView(x.dataset.view)}));
const initial=location.hash.slice(1);showView(['bellwork','fast','explore'].includes(initial)?initial:'home');

const dayPlans={
  1:{name:'Monday · Make a Claim',standard:'ELA.6.R.2.4',label:'Argument',goal:'5–7 complete sentences',prompt:'Should sixth-grade students have a short independent reading period every school day? State a clear claim and support it with two logical reasons.',starter:'Sixth-grade students should/should not ___ because ___.'},
  2:{name:'Tuesday · Read Between the Lines',standard:'ELA.6.R.1.1',label:'Inference',goal:'4–6 complete sentences',prompt:'A character says, “It does not matter,” but folds the note carefully and places it in a desk drawer. What can you infer about the note? Use two details from the sentence.',starter:'Readers can infer that ___ because the character ___ and ___.'},
  3:{name:'Wednesday · Word Detective',standard:'ELA.6.V.1.2',label:'Morphology & Context',goal:'4–6 complete sentences',prompt:'In the sentence “The hikers were rejuvenated after resting beside the cool stream,” what does rejuvenated mean? Explain how the word parts or context helped you decide.',starter:'Rejuvenated most likely means ___. The clue ___ helped me because ___.'},
  4:{name:'Thursday · Explain the Evidence',standard:'ELA.6.R.2.2',label:'Central Idea',goal:'5–7 complete sentences',prompt:'A community garden provides fresh food, gives neighbors a place to work together, and creates habitat for pollinators. What central idea connects these details? Explain how two details develop it.',starter:'The central idea is ___. The details ___ and ___ develop this idea by ___.'},
  5:{name:'Friday · Reflect & Revise',standard:'ELA.6.C.4.1',label:'Improving Writing',goal:'4–6 complete sentences',prompt:'What reading or writing strategy helped you most this week? Describe when you used it, why it worked, and one way you will improve it next week.',starter:'The strategy that helped me most was ___. It worked when ___ because ___.'}
};
function planForToday(){const day=new Date().getDay();return dayPlans[day]||dayPlans[1]}
const plan=planForToday(),todayKey=new Date().toLocaleDateString('en-CA'),response=document.querySelector('#bell-response');
document.querySelector('#home-focus').textContent=plan.prompt;
document.querySelector('#bell-day-type').textContent=plan.name;document.querySelector('#bell-prompt').textContent=plan.prompt;document.querySelector('#bell-label').textContent=`${plan.standard} · ${plan.label}`;document.querySelector('#response-goal').textContent=plan.goal;document.querySelector('#sentence-starter').textContent=plan.starter;document.querySelector('#bell-date').textContent=new Date().toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'});
function draftKey(){return `bakerBellwork:${authState.user?.uid||'signed-out'}:${todayKey}`}
function stats(){const text=response.value.trim(),words=text?text.split(/\s+/).length:0,sentences=(text.match(/[.!?]+(?=\s|$)/g)||[]).length;document.querySelector('#word-count').textContent=words;document.querySelector('#sentence-count').textContent=sentences;return words}
response.addEventListener('input',()=>{localStorage.setItem(draftKey(),response.value);stats()});
document.querySelector('#starter-toggle').addEventListener('click',()=>document.querySelector('#sentence-starter').toggleAttribute('hidden'));
document.querySelector('#bellwork-signin').addEventListener('click',()=>document.querySelector('#account-dialog').showModal());
function openBellwork(){const allowed=authState.user&&authState.classCode;document.querySelector('#bellwork-gate').hidden=Boolean(allowed);document.querySelector('#bellwork-workspace').hidden=!allowed;if(allowed){response.value=localStorage.getItem(draftKey())||'';stats();loadHistory()}}
function ready(){return stats()>=20&&['check-answer','check-evidence','check-revise'].every(id=>document.querySelector(`#${id}`).checked)&&document.querySelector('#confidence').value}
document.querySelector('#submit-bellwork').addEventListener('click',async()=>{const message=document.querySelector('#submission-message');if(!ready()){message.textContent='Before submitting, write at least 20 words, complete all three checks, and choose a confidence level.';return}message.textContent='Submitting...';try{await authState.api.addDoc(authState.api.collection(authState.db,'bellwork'),{studentUid:authState.user.uid,studentName:authState.user.displayName||'Student',classCode:authState.classCode,date:todayKey,standard:plan.standard,label:plan.label,prompt:plan.prompt,response:response.value.trim(),wordCount:stats(),confidence:Number(document.querySelector('#confidence').value),status:'submitted',submittedAt:authState.api.serverTimestamp()});message.textContent='Submitted to Mrs. Baker. Nice work.';await loadHistory()}catch(e){message.textContent='Submission did not save. Your draft is still safe on this device.'}});
async function loadHistory(){if(!authState.user||!authState.api)return;try{const q=authState.api.query(authState.api.collection(authState.db,'bellwork'),authState.api.where('studentUid','==',authState.user.uid)),snap=await authState.api.getDocs(q),items=snap.docs.map(d=>d.data()).sort((a,b)=>(b.date||'').localeCompare(a.date||'')).slice(0,10);document.querySelector('#history-count').textContent=items.length;document.querySelector('#bell-history-list').innerHTML=items.length?items.map(x=>`<article><b>${escapeHtml(x.date)} · ${escapeHtml(x.label)}</b><p>${escapeHtml(x.response)}</p><small>${x.wordCount||0} words · Confidence ${x.confidence||'—'}/4</small></article>`).join(''):'<p>No submitted bell work yet.</p>'}catch(e){document.querySelector('#bell-history-list').innerHTML='<p>Submitted work will appear here.</p>'}}
function escapeHtml(v){const d=document.createElement('div');d.textContent=String(v||'');return d.innerHTML}
window.addEventListener('baker-auth-change',({detail})=>{Object.assign(authState,detail);openBellwork();loadLeaderboard()});

function leaderboardName(name){const parts=String(name||'Student').trim().split(/\s+/);return parts.length>1?`${parts[0]} ${parts.at(-1)[0]}.`:parts[0]}
async function loadLeaderboard(){if(!authState.api||!authState.db)return;try{const q=authState.api.query(authState.api.collection(authState.db,'leaderboard'),authState.api.orderBy('bestStreak','desc'),authState.api.limit(10)),snap=await authState.api.getDocs(q),items=snap.docs.map(d=>d.data());document.querySelector('#leaderboard-list').innerHTML=items.length?items.map((x,i)=>`<li data-rank="${i+1}"><b>${escapeHtml(x.displayName)}</b><span>${escapeHtml(x.classCode||'Mrs. Baker’s ELA')}</span><b>${x.bestStreak} in a row</b></li>`).join(''):'<li class="leaderboard-empty">Be the first student to set a class streak.</li>'}catch(e){document.querySelector('#leaderboard-list').innerHTML='<li class="leaderboard-empty">The leaderboard will appear after class accounts are connected.</li>'}}
async function saveBestStreak(){if(!authState.user||!authState.classCode||!authState.api||streak<2)return;try{const ref=authState.api.doc(authState.db,'leaderboard',authState.user.uid),current=await authState.api.getDoc(ref),best=current.data()?.bestStreak||0;if(streak>best){await authState.api.setDoc(ref,{uid:authState.user.uid,displayName:leaderboardName(authState.user.displayName),classCode:authState.classCode,bestStreak:streak,updatedAt:authState.api.serverTimestamp()},{merge:true});loadLeaderboard()}}catch(e){}}

const passages=[
 {type:'Informational',standard:'ELA.6.R.2.2',text:'Each spring, horseshoe crabs crawl onto beaches to lay eggs. Migrating shorebirds arrive at nearly the same time and depend on those eggs for energy during their long journeys. When horseshoe crab numbers fall, some bird populations struggle too.',qs:[['Which central idea is best supported?',['Horseshoe crabs and shorebirds are connected in an important food relationship.','All shorebirds live only on beaches.','Horseshoe crabs migrate farther than birds.','Spring weather makes animals struggle.'],0,'The passage connects horseshoe crab eggs directly to the survival of migrating shorebirds.'],['Why does the author mention when the birds arrive?',['To explain why beaches are warm','To show that timing makes the eggs an important food source','To prove birds lay eggs in spring','To compare two migration distances'],1,'The matching timing explains why the crabs’ eggs matter to the birds.'],['What can be inferred if crab numbers recover?',['Some shorebirds may have more food during migration.','All beach animals will leave.','The birds will stop migrating.','Spring will begin earlier.'],0,'More crabs can mean more eggs, which the passage identifies as migration fuel.'],['Which detail best develops the central idea?',['Each spring','crawl onto beaches','shorebirds depend on those eggs for energy','during their long journeys'],2,'That detail explicitly shows the relationship between the two animals.']]},
 {type:'Literary',standard:'ELA.6.R.1.1',text:'Maya stood behind the curtain, turning her note cards over and over. When her name was announced, she tucked the cards into her pocket, stepped toward the microphone, and began the speech from memory. Her first sentence trembled, but the second rang clearly across the room.',qs:[['How does Maya change?',['She becomes less prepared.','She moves from nervousness toward confidence.','She decides not to speak.','She becomes angry with the audience.'],1,'Her trembling start followed by a clear sentence shows growing confidence.'],['Which detail best shows Maya is nervous?',['Her name was announced.','She stood behind a curtain.','She turned her note cards over and over.','She spoke from memory.'],2,'The repeated motion is a physical clue to her nervousness.'],['Why does Maya put away the cards?',['She forgot how to read.','She wants to challenge herself to speak from memory.','The cards are incorrect.','The audience cannot see them.'],1,'Her next action, beginning from memory, supports this inference.'],['What theme is beginning to develop?',['Preparation can help someone act despite fear.','Speaking is always easy.','Audiences dislike note cards.','Memories are unreliable.'],0,'Maya is prepared, still afraid, and chooses to act anyway.']]},
 {type:'Informational',standard:'ELA.6.R.2.1',text:'A city library created a “library of things” beside its shelves of books. Residents can borrow tools, sewing machines, board games, and baking pans. The program saves families money and reduces waste because many people share items that would otherwise be purchased and rarely used.',qs:[['How is the passage mainly organized?',['Chronological order','Cause and effect','Problem and solution','Compare and contrast'],2,'The program is presented as a solution that saves money and reduces waste.'],['What is the main purpose of the examples?',['To show the variety of useful items people can borrow','To explain how books are printed','To prove board games are expensive','To list items the library sells'],0,'The list illustrates what “things” means in this unusual library.'],['Which is the best summary?',['Libraries should stop lending books.','A library lends shared household items, helping residents save money and reduce waste.','Baking pans are the most popular library items.','Families rarely use tools.'],1,'It includes the program and both important benefits without minor details.'],['What does otherwise mean here?',['In a different situation','Very quickly','At the library','Without payment'],0,'The sentence means the items would be bought in a different situation.']]},
 {type:'Literary',standard:'ELA.6.R.1.2',text:'Leo planted three sunflower seeds in a chipped blue pot. For weeks, nothing appeared. His brother told him to throw the soil away, but Leo kept watering it each morning. One rainy Tuesday, a green hook finally pushed through the dirt.',qs:[['Which theme is best supported?',['Patience and steady effort can lead to results.','Rain ruins careful plans.','Brothers always disagree.','Old pots cannot grow plants.'],0,'Leo continues caring for the seeds despite seeing no immediate result.'],['Which detail most clearly develops the theme?',['The pot is blue.','Leo keeps watering even when nothing appears.','Tuesday is rainy.','There are three seeds.'],1,'His repeated effort is the key evidence for perseverance.'],['What does the green hook refer to?',['A garden tool','A new plant sprout','A piece of the pot','A worm'],1,'Its movement through the dirt after watering identifies it as a sprout.'],['How does the brother affect the plot?',['He waters the plant.','His doubt creates a choice for Leo to quit or continue.','He breaks the pot.','He plants another seed.'],1,'The brother’s advice creates a moment when Leo must choose persistence.']]},
 {type:'Informational',standard:'ELA.6.R.2.3',text:'One article argues that school gardens improve science learning because students observe ecosystems directly. Another article supports gardens because growing vegetables can expand access to fresh food. Both authors favor gardens, but they emphasize different benefits.',qs:[['How do the authors’ purposes differ?',['One emphasizes learning; the other emphasizes food access.','One opposes gardens; the other supports them.','Both focus only on cost.','Both explain how to plant seeds.'],0,'The passage directly names the different benefits each author emphasizes.'],['What do both authors agree about?',['Gardens are difficult to maintain.','Schools should have gardens.','Science is the only useful subject.','Vegetables should be free.'],1,'The final sentence states that both favor gardens.'],['Which text structure dominates?',['Sequence','Cause and effect','Compare and contrast','Description'],2,'The passage identifies a similarity and a difference between two articles.'],['What does emphasize mean?',['To give special importance to','To disagree loudly','To remove evidence','To repeat word for word'],0,'Each author gives special importance to a different benefit.']]},
 {type:'Literary',standard:'ELA.6.R.1.3',text:'I insisted the shortcut through the field would save us ten minutes. Halfway across, mud swallowed my left shoe. My cousin stood on the dry sidewalk, trying not to laugh. “Excellent navigation,” she called while I hopped back for the shoe.',qs:[['How does first-person point of view affect the passage?',['It lets readers experience the narrator’s mistaken confidence directly.','It reveals every character’s private thoughts.','It makes the passage a news report.','It prevents humor.'],0,'The narrator admits the poor decision and describes the embarrassing result firsthand.'],['The cousin’s words are an example of—',['a sincere compliment','verbal irony','a scientific claim','a flashback'],1,'She says the opposite of what she means after the shortcut fails.'],['What tone does the passage create?',['Threatening','Humorous','Formal','Mysterious'],1,'The lost shoe, hopping, and ironic comment make the event playful.'],['Which detail best reveals the narrator’s original attitude?',['mud swallowed my shoe','I insisted the shortcut would save time','my cousin stood on the sidewalk','I hopped back'],1,'“Insisted” shows strong confidence before the plan fails.']]},
 {type:'Vocabulary',standard:'ELA.6.V.1.2',text:'After weeks without rain, the brittle grass crunched under every step. Gardeners conserved water by collecting the small amount that dripped from air conditioners and using it on their most delicate plants.',qs:[['What does conserved mean?',['Used carelessly','Saved and used carefully','Heated quickly','Poured away'],1,'The gardeners collect limited water and direct it where it is most needed.'],['Which context clue best supports the meaning of brittle?',['weeks without rain','gardeners conserved','air conditioners','delicate plants'],0,'A long dry period explains why the grass is dry enough to break or crunch.'],['Which word is closest in meaning to delicate?',['Fragile','Enormous','Common','Artificial'],0,'Delicate plants are easily harmed and need careful treatment.'],['How does the suffix -ed function in conserved?',['It shows a past action.','It means without.','It changes the word into a person.','It means again.'],0,'The suffix marks the verb as happening in the past.']]},
 {type:'Argument',standard:'ELA.6.R.2.4',text:'The student council proposes adding refill stations for water bottles. The group argues that stations would reduce plastic waste and make drinking water easier to access. Their survey found that 68 percent of students already carry reusable bottles at least twice a week.',qs:[['Which evidence most directly supports easier access?',['Plastic can become waste.','Many students already carry reusable bottles.','The student council meets weekly.','Surveys use percentages.'],1,'Students who already carry bottles could readily use refill stations.'],['What is the council’s main claim?',['Schools should sell more plastic bottles.','Adding refill stations would benefit the school.','Students dislike drinking water.','Surveys should happen twice a week.'],1,'The reasons about waste and access support installing the stations.'],['Which additional evidence would best strengthen the argument?',['The color of current fountains','The cost and expected use of refill stations','A list of council members','The history of plastic'],1,'Cost and expected use would help evaluate whether the proposal is practical and useful.'],['Why is the survey relevant?',['It shows many potential users already have reusable bottles.','It proves all students agree.','It explains how plastic is made.','It compares two schools.'],0,'The survey establishes a likely group of students who would use the stations.']]},
 {type:'Poetry',standard:'ELA.6.R.1.4',text:'The morning folds its silver map,\nacross the waking bay;\none bright path trembles on the waves,\nthen slowly points the way.',qs:[['What is being personified?',['Morning','A map','A path','The waves'],0,'Morning is given the humanlike ability to fold and present a map.'],['What does the silver map most likely represent?',['A paper map','Sunlight spreading over the water','A fishing net','Clouds covering the bay'],1,'The bright path across waking water suggests reflected morning light.'],['How does the four-line form affect the poem?',['It presents one focused image in a brief moment.','It explains a long historical event.','It creates a debate between speakers.','It gives detailed instructions.'],0,'The compact stanza concentrates attention on a single sunrise image.'],['Which mood is created?',['Peaceful and hopeful','Angry and loud','Confused and frantic','Gloomy and hopeless'],0,'Words such as waking, bright, and points the way create calm hopefulness.']]},
 {type:'Informational',standard:'ELA.6.R.2.2',text:'Mangrove roots form tangled walls along Florida shorelines. The roots slow waves, trap sediment, and provide hiding places for young fish. During storms, mangrove forests can also reduce some of the energy that reaches coastal communities.',qs:[['Which is the best central idea?',['Mangroves protect and support coastal environments in several ways.','All fish live in mangrove roots.','Storms only happen near forests.','Sediment damages every shoreline.'],0,'The passage lists multiple ecological and protective benefits.'],['Which detail shows a benefit to animals?',['The roots slow waves.','The roots trap sediment.','The roots provide hiding places for young fish.','Forests reduce energy.'],2,'The hiding places directly support young fish.'],['What relationship does the passage show?',['Mangrove features cause several shoreline benefits.','Fish cause storms.','Sediment removes roots.','Communities plant waves.'],0,'The physical roots lead to reduced waves, trapped sediment, and habitat.'],['What does coastal mean?',['Related to land near the sea','Located underground','Far from water','Made by young fish'],0,'Shorelines, waves, and storms provide context for land near the sea.']]},
 {type:'Literary',standard:'ELA.6.R.1.1',text:'Nia had practiced the piano piece until her family could hum every measure. At the recital, the bench felt too high and the lights too bright. She missed one note, paused, and heard her teacher whisper, “Keep going.” Nia took a breath and found the next measure.',qs:[['Which event is the turning point?',['Her family learns the tune.','The bench feels high.','She hears “Keep going” and resumes playing.','The lights are bright.'],2,'The encouragement changes her from pausing after a mistake to continuing.'],['What conflict does Nia face?',['Person versus nature','Person versus self','Person versus society','Person versus technology'],1,'She must manage her own fear and response to making a mistake.'],['Which theme is supported?',['A mistake does not have to end an effort.','Practice guarantees perfection.','Bright lights improve music.','Teachers should perform for students.'],0,'Nia makes a mistake, recovers, and continues.'],['How does the setting influence Nia?',['The recital environment increases her nervousness.','The piano is outdoors.','Her family leaves the room.','The bench makes the music easier.'],0,'The unfamiliar bench and bright stage lights contribute to her discomfort.']]},
 {type:'Argument',standard:'ELA.6.R.2.4',text:'A writer claims that students should help choose some library purchases. She explains that students are more likely to read books connected to their interests. She also notes that librarians would still review every suggestion for age appropriateness and quality.',qs:[['Which sentence states the claim?',['Students should help choose some library purchases.','Students have many interests.','Librarians read books.','Every suggestion has a title.'],0,'That statement is the position the remaining reasons support.'],['Why does the writer mention librarian review?',['To address a concern about unsuitable choices','To prove students cannot read','To explain library hours','To criticize book quality'],0,'The detail answers a likely concern while preserving professional review.'],['Which is a reason supporting the claim?',['Libraries contain shelves.','Students may read more when books match their interests.','All books are the same quality.','Suggestions must be handwritten.'],1,'Greater interest and reading is the stated benefit.'],['What counterclaim is the writer most likely responding to?',['Students may suggest books that are not appropriate or useful.','Libraries have no books.','Students dislike having choices.','Librarians never review purchases.'],0,'The assurance that librarians review suggestions directly addresses that concern.']]},
 {type:'Informational',standard:'ELA.6.R.2.1',text:'At first, scientists counted manatees from boats and airplanes. Today, some researchers also use drones to photograph shallow water from above. Computer programs help compare the images, but trained scientists still review the results because glare, waves, and shadows can be mistaken for animals.',qs:[['How does the passage develop information?',['It contrasts an earlier method with newer tools.','It lists events in a manatee’s life.','It argues that airplanes should be banned.','It describes only computer software.'],0,'The passage moves from earlier counting methods to current drone and computer support.'],['Why must scientists still review the images?',['Drones cannot take photographs.','Conditions in the water can create misleading shapes.','Manatees always hide under boats.','Computer programs count only shadows.'],1,'The final clause names glare, waves, and shadows as possible sources of mistakes.'],['Which is the best summary?',['Technology helps researchers count manatees, but human review remains important.','Scientists no longer use boats.','Shallow water contains no glare.','Airplanes are more accurate than every other tool.'],0,'It captures both the benefit of technology and the need for expert checking.'],['What does trained imply about the scientists?',['They have practiced and developed specialized knowledge.','They travel only by train.','They are new to the work.','They avoid using evidence.'],0,'Reviewing difficult images accurately requires learned expertise.']]}
];
const questionBank=passages.flatMap((p,pi)=>p.qs.map((q,qi)=>({id:`${pi}-${qi}`,type:p.type,standard:p.standard,passage:p.text,question:q[0],answers:q[1],correct:q[2],explanation:q[3]})));
let fastOrder=[],fastIndex=0,score=0,streak=0,skillScores={};
function shuffle(a){return [...a].sort(()=>Math.random()-.5)}
function resetFast(){fastOrder=shuffle(questionBank);fastIndex=score=streak=0;skillScores={};renderQuestion();updateGame()}
function renderQuestion(){if(fastIndex>=fastOrder.length)fastOrder=shuffle(questionBank),fastIndex=0;const q=fastOrder[fastIndex];document.querySelector('#fast-category').textContent=q.type;document.querySelector('#fast-standard').textContent=q.standard;document.querySelector('#fast-passage').innerHTML=escapeHtml(q.passage).replaceAll('\n','<br>');document.querySelector('#fast-question').textContent=q.question;document.querySelector('#fast-answers').innerHTML=q.answers.map((a,i)=>`<button data-answer="${i}"><b>${String.fromCharCode(65+i)}</b> ${escapeHtml(a)}</button>`).join('');document.querySelector('#fast-feedback').textContent='Choose the answer that the text supports best.';document.querySelector('#fast-next').hidden=true;document.querySelectorAll('[data-answer]').forEach(b=>b.addEventListener('click',()=>answerQuestion(Number(b.dataset.answer))))}
function answerQuestion(choice){const q=fastOrder[fastIndex],correct=choice===q.correct;document.querySelectorAll('[data-answer]').forEach((b,i)=>{b.disabled=true;if(i===q.correct)b.classList.add('correct');else if(i===choice)b.classList.add('incorrect')});if(correct){score+=10+Math.min(streak,5)*2;streak++;skillScores[q.type]=(skillScores[q.type]||0)+1;saveBestStreak()}else streak=0;document.querySelector('#fast-feedback').innerHTML=`<b>${correct?'Correct!':'Not quite.'}</b> ${escapeHtml(q.explanation)}`;document.querySelector('#fast-next').hidden=false;updateGame()}
function updateGame(){document.querySelector('#fast-score').textContent=score;document.querySelector('#fast-streak').textContent=streak;document.querySelector('#fast-count').textContent=fastIndex;const best=Object.entries(skillScores).sort((a,b)=>b[1]-a[1])[0];document.querySelector('#fast-best').textContent=best?best[0]:'Start playing'}
document.querySelector('#fast-next').addEventListener('click',()=>{fastIndex++;renderQuestion();updateGame()});document.querySelector('#fast-reset').addEventListener('click',resetFast);resetFast();
document.querySelectorAll('[data-panel]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-panel]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.explore-panel').forEach(x=>x.classList.toggle('active',x.id===`panel-${b.dataset.panel}`))}));
