
const bellPrompts=[
  {standard:"ELA.6.R.1.1",label:"Literary Elements",prompt:"Think of a character from a story you know. What is one choice the character makes, and how does that choice affect what happens next?",starter:"The character’s choice to ___ affects the story because ___.",goal:"4–6 complete sentences"},
  {standard:"ELA.6.R.1.2",label:"Theme",prompt:"What lesson can a person learn from making a difficult choice? Explain the lesson and give a specific example from a story, movie, or real situation.",starter:"A lesson someone can learn is ___ because ___ . For example, ___ .",goal:"5–7 complete sentences"},
  {standard:"ELA.6.R.2.2",label:"Central Idea",prompt:"Why is belonging important to people? State one central idea and develop it with two relevant details or examples.",starter:"Belonging is important because ___. One example is ___, and another is ___ .",goal:"5–7 complete sentences"},
  {standard:"ELA.6.R.2.4",label:"Argument",prompt:"Should students be allowed to listen to music while working independently? Make a clear claim and support it with two reasons.",starter:"Students should / should not be allowed to ___ because ___ .",goal:"5–7 complete sentences"},
  {standard:"ELA.6.R.3.1",label:"Figurative Language",prompt:"Write a simile or metaphor that describes the first ten minutes of a school day. Then explain how the comparison creates a specific tone.",starter:"The first ten minutes are like ___. This creates a ___ tone because ___ .",goal:"3–5 complete sentences"},
  {standard:"ELA.6.R.3.4",label:"Rhetoric",prompt:"Choose a school rule. How might a speaker use logic, emotion, or credibility to persuade students to follow it?",starter:"A speaker could use ___ by ___ . This would persuade students because ___ .",goal:"4–6 complete sentences"},
  {standard:"ELA.6.V.1.3",label:"Context and Connotation",prompt:"Use the word reluctant in a sentence with enough context for a reader to infer its meaning. Then explain which words provide the clue.",starter:"Although ___, I was reluctant to ___ because ___. The words ___ show that reluctant means ___ .",goal:"3–4 complete sentences"},
  {standard:"ELA.6.C.1.3",label:"Argumentative Writing",prompt:"What is one change that would improve the school day? State a claim, support it with a reason, and address one possible concern.",starter:"The school should ___. This would help because ___. Some may worry ___, but ___ .",goal:"6–8 complete sentences"}
];
const agenda={today:[['5 min','Bell Work','Respond, revise, and be ready to share.'],['10 min','Mini Lesson','Model today’s reading or writing skill.'],['25 min','StudySync Practice','Read, annotate, discuss, and apply the skill.'],['8 min','Small Group / Independent','Targeted practice or conference.'],['2 min','Exit Ticket','Name what you learned and your next step.']],week:[['Mon','Launch the skill','Teacher model + guided practice'],['Tue','Close reading','Annotate and gather evidence'],['Wed','Small groups','Targeted reteach and vocabulary'],['Thu','Write from reading','Claim, evidence, and reasoning'],['Fri','Check growth','Short assessment, reflection, and retry']],month:[['Week 1','Build background','Vocabulary, purpose, and first reads'],['Week 2','Read closely','Craft, structure, and evidence'],['Week 3','Write & discuss','Develop and defend ideas'],['Week 4','Show growth','Revise, assess, reflect, and celebrate'] ]};
const strands={
  literature:{title:"Reading Prose & Poetry",codes:"ELA.6.R.1.1–1.4",intro:"Analyze literary elements, theme, perspective, point of view, and poetic form.",skills:["Explain how character development and setting affect plot","Analyze a theme and its development","Explain the influence of narrator perspective and point of view","Describe how poetic form affects meaning and style"],success:"I can make an idea about a literary text and prove it with the strongest details.",fast:"Reading Prose and Poetry makes up approximately 25–35% of Grade 6 FAST ELA Reading."},
  information:{title:"Reading Informational Text",codes:"ELA.6.R.2.1–2.4",intro:"Analyze structure, central ideas, author purpose, perspective, and argument.",skills:["Explain how sections and features convey meaning","Analyze explicit or implied central ideas","Compare authors’ purposes across accounts","Track an argument and identify its reasoning"],success:"I can explain an important idea and show exactly how the author develops it.",fast:"Reading Informational Text makes up approximately 25–35% of Grade 6 FAST ELA Reading."},
  writing:{title:"Communication & Writing",codes:"ELA.6.C.1.2–1.5 · C.3.1 · C.4.1",intro:"Write narratives, arguments, and expository texts; revise purposefully; use conventions and research responsibly.",skills:["Write narratives using effective techniques","Support argumentative and expository writing with evidence","Revise for clarity, organization, and style","Use conventions and information ethically"],success:"I can make purposeful choices and improve my work using feedback.",fast:"B.E.S.T. Writing measures argumentative or expository writing, conventions, research, vocabulary, and reading skills."},
  vocabulary:{title:"Vocabulary",codes:"ELA.6.V.1.1–1.3",intro:"Use academic vocabulary, morphology, context, connotation, and word relationships to determine meaning.",skills:["Use grade-level academic vocabulary","Apply Greek and Latin roots and affixes","Use context clues and word relationships","Explain how connotation shapes meaning"],success:"I can explain how I determined a word’s meaning instead of only guessing.",fast:"Morphology and context/connotation are assessed within Reading Across Genres and Vocabulary."},
  communication:{title:"Creating, Speaking & Collaborating",codes:"ELA.6.C.2.1 · C.5.1–5.2 · ELA.K12.EE.4.1",intro:"Present ideas clearly, create multimedia work, use technology responsibly, and collaborate through active listening.",skills:["Organize an oral presentation for purpose and audience","Use multimedia elements to strengthen meaning","Use digital tools to create and collaborate","Listen actively and respond with evidence"],success:"I can help a group think better, not simply talk more.",fast:"Speaking and collaboration support the evidence, reasoning, and comprehension used across ELA."}
};
const toolData={
  evidence:{title:"Evidence Builder",description:"Click a purpose to get a sentence frame you can adapt.",items:[["Introduce evidence","The text states, “___,” which shows..."],["Explain evidence","This detail matters because..."],["Make an inference","Readers can infer ___ because the author reveals..."],["Compare ideas","Both texts show ___; however, they differ because..."]]},
  paragraph:{title:"Paragraph Planner",description:"Build in this order. Each move should do a different job.",items:[["1 · Point","Make a focused claim that answers the question."],["2 · Proof","Choose a detail or quotation that directly supports it."],["3 · Reasoning","Explain how the proof supports the point."],["4 · Link","Connect the paragraph back to the larger idea."]]},
  vocab:{title:"Word Solver",description:"When a word is unfamiliar, try these clues before reaching for a dictionary.",items:[["Read around it","Look before and after the word for examples or contrasts."],["Break it apart","Find a prefix, root, or suffix you recognize."],["Test a synonym","Replace it with a possible meaning and reread."],["Check the tone","Decide whether the word feels positive, negative, or neutral."]]},
  discussion:{title:"Discussion Stems",description:"Use language that makes conversation clearer and more thoughtful.",items:[["Build on","I’d like to add to ___’s idea because..."],["Disagree thoughtfully","I see it differently because the text suggests..."],["Ask for proof","Which detail led you to that conclusion?"],["Clarify","When you say ___, do you mean...?"]]}
};
const bellResponse=document.querySelector('#bell-response');
const todayKey=new Date().toLocaleDateString('en-CA');
let bellIndex=Math.abs([...todayKey].reduce((total,char)=>total+char.charCodeAt(0),0))%bellPrompts.length;
let authState={ready:false,user:null,db:null,classCode:"",api:null};
const draftKey=()=>`bakerBellwork:${authState.user?.uid||'device'}:${todayKey}:${bellIndex}`;
function currentPrompt(){return bellPrompts[bellIndex]}
function renderBellPrompt(){const item=currentPrompt();document.querySelector('#bell-label').textContent=`${item.standard} · ${item.label}`;document.querySelector('#bell-prompt').textContent=item.prompt;document.querySelector('#sentence-starter').textContent=item.starter;document.querySelector('#response-goal').textContent=item.goal;bellResponse.value=localStorage.getItem(draftKey())||'';updateWritingStats()}
function sentenceCount(text){return (text.match(/[.!?]+(?=\s|$)/g)||[]).length}
function updateWritingStats(){const words=bellResponse.value.trim()?bellResponse.value.trim().split(/\s+/).length:0;const sentences=sentenceCount(bellResponse.value);const stepIndex=!words?0:words<25?1:readyToSubmit()?3:2;document.querySelector('#word-count').textContent=words;document.querySelector('#sentence-count').textContent=sentences;document.querySelector('#writing-meter-fill').style.width=`${Math.min(100,words/60*100)}%`;document.querySelectorAll('.bell-progress span').forEach((step,index)=>step.classList.toggle('active',index===stepIndex));}
function readyToSubmit(){return bellResponse.value.trim().split(/\s+/).length>=20&&['check-answer','check-evidence','check-revise'].every(id=>document.querySelector(`#${id}`).checked)&&Boolean(document.querySelector('#confidence').value)}
function updateChecklist(){const checked=['check-answer','check-evidence','check-revise'].filter(id=>document.querySelector(`#${id}`).checked).length;document.querySelector('#check-summary').textContent=`${checked} of 3 ready`;updateWritingStats()}
function saveDraft(){localStorage.setItem(draftKey(),bellResponse.value);document.querySelector('#save-status').textContent='Draft saved';}
document.querySelector('#bell-date').textContent=new Date().toLocaleDateString('en-US',{weekday:'short',month:'short',day:'numeric'});
bellResponse.addEventListener('input',()=>{updateWritingStats();saveDraft()});
['check-answer','check-evidence','check-revise'].forEach(id=>document.querySelector(`#${id}`).addEventListener('change',updateChecklist));
document.querySelector('#confidence').addEventListener('change',updateWritingStats);
document.querySelector('#clear-response').addEventListener('click',()=>{if(!bellResponse.value||confirm('Clear this draft?')){bellResponse.value='';localStorage.removeItem(draftKey());updateWritingStats();document.querySelector('#save-status').textContent='Cleared';}});
document.querySelector('#new-bellwork').addEventListener('click',()=>{bellIndex=(bellIndex+1)%bellPrompts.length;renderBellPrompt();document.querySelector('#submission-message').textContent='Practice prompts save as private drafts and are not today’s assigned submission.';});
document.querySelector('#submit-bellwork').addEventListener('click',async()=>{const message=document.querySelector('#submission-message');if(!authState.user){document.querySelector('#account-dialog').showModal();message.textContent='Sign in with your school account before submitting.';return}if(!authState.classCode){document.querySelector('#account-dialog').showModal();message.textContent='Join Mrs. Baker’s class before submitting.';return}if(!readyToSubmit()){message.textContent='Finish at least 20 words, all three checks, and the confidence reflection.';return}const item=currentPrompt();message.textContent='Submitting…';try{await authState.api.addDoc(authState.api.collection(authState.db,'bellwork'),{studentUid:authState.user.uid,studentName:authState.user.displayName||'Student',classCode:authState.classCode,date:todayKey,promptIndex:bellIndex,standard:item.standard,label:item.label,prompt:item.prompt,response:bellResponse.value.trim(),wordCount:Number(document.querySelector('#word-count').textContent),confidence:Number(document.querySelector('#confidence').value),status:'submitted',submittedAt:authState.api.serverTimestamp()});message.textContent='Submitted to Mrs. Baker. Nice work. You can still review your response below.';document.querySelector('#save-status').textContent='Submitted';await loadBellHistory()}catch(error){message.textContent='Submission did not save. Your draft is safe on this device; please try again.';}});
async function loadBellHistory(){if(!authState.user||!authState.api)return;const q=authState.api.query(authState.api.collection(authState.db,'bellwork'),authState.api.where('studentUid','==',authState.user.uid));const snap=await authState.api.getDocs(q);const items=snap.docs.map(x=>x.data()).sort((a,b)=>(b.date||'').localeCompare(a.date||'')).slice(0,8);document.querySelector('#history-count').textContent=items.length;document.querySelector('#bell-history-list').innerHTML=items.length?items.map(x=>`<article><span>${x.date}</span><b>${x.standard} · ${x.label}</b><p>${x.response}</p><small>${x.wordCount||0} words · Confidence ${x.confidence||'—'}/4</small></article>`).join(''):'<p>No submitted bell work yet.</p>'}
window.addEventListener('baker-auth-change',async({detail})=>{const draftInProgress=bellResponse.value;authState={...authState,...detail};if(authState.user&&draftInProgress&&!localStorage.getItem(draftKey()))localStorage.setItem(draftKey(),draftInProgress);document.querySelector('#draft-owner').textContent=authState.user?`Draft for ${authState.user.displayName?.split(' ')[0]||'student'}`:'Private device draft';document.querySelector('#submission-message').textContent=authState.user?(authState.classCode?'Ready to submit to Mrs. Baker.':'Enter your class code in your account to submit.'):'Sign in to submit. You can still draft on this device.';renderBellPrompt();if(authState.user)await loadBellHistory()});
renderBellPrompt();
let seconds=300,timerId=null;function drawTimer(){const m=String(Math.floor(seconds/60)).padStart(2,'0'),s=String(seconds%60).padStart(2,'0');document.querySelector('#timer-display').textContent=`${m}:${s}`}
document.querySelector('#timer-button').addEventListener('click',e=>{if(timerId){clearInterval(timerId);timerId=null;e.target.textContent='Start';return}e.target.textContent='Pause';timerId=setInterval(()=>{if(seconds>0){seconds--;drawTimer()}else{clearInterval(timerId);timerId=null;e.target.textContent='Done'}},1000)});
document.querySelector('#timer-reset').addEventListener('click',()=>{clearInterval(timerId);timerId=null;seconds=300;drawTimer();document.querySelector('#timer-button').textContent='Start'});
function renderAgenda(key){document.querySelector('#agenda-content').innerHTML=agenda[key].map(x=>`<div class="agenda-item"><span>${x[0]}</span><div><b>${x[1]}</b><small>${x[2]}</small></div></div>`).join('')};renderAgenda('today');
document.querySelector('#agenda-date').textContent=new Date().toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'});
document.querySelectorAll('[data-agenda]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-agenda]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderAgenda(b.dataset.agenda)}));
function renderStrand(key){const s=strands[key];document.querySelector('#strand-detail').innerHTML=`<div><p class="eyebrow pink">Official Florida B.E.S.T. benchmarks</p><h3>${s.title}</h3><p><b>${s.codes}</b></p><p>${s.intro}</p><ul>${s.skills.map(x=>`<li>✓ ${x}</li>`).join('')}</ul><a href="https://www.fldoe.org/core/fileparse.php/7539/urlt/elabeststandardsfinal.pdf#page=79" target="_blank" rel="noreferrer">Open the official Grade 6 B.E.S.T. standards ↗</a></div><div class="success-box"><b>What success sounds like</b><h3>“${s.success}”</h3><p><strong>FAST connection:</strong> ${s.fast}</p></div>`};renderStrand('literature');
document.querySelectorAll('[data-strand]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-strand]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderStrand(b.dataset.strand)}));
document.querySelectorAll('#fast-answers button').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('#fast-answers button').forEach(x=>x.classList.remove('correct','wrong'));const good=b.dataset.correct==='true';b.classList.add(good?'correct':'wrong');document.querySelector('#fast-feedback').innerHTML=good?'<b>Correct.</b> The passage says the cleanup helps immediately and also aims to change everyday choices.':'<b>Not quite.</b> This choice is too narrow or unsupported. Look for an answer that includes both the immediate cleanup and its larger purpose.'}));
function renderTool(key){const t=toolData[key];document.querySelector('#tool-panel').innerHTML=`<h3>${t.title}</h3><p>${t.description}</p><div class="stem-grid">${t.items.map((x,i)=>`<button class="stem-card" data-stem="${i}"><b>${x[0]}</b>${x[1]}</button>`).join('')}</div><div class="stem-output" id="stem-output">Choose a tool above.</div>`;document.querySelectorAll('[data-stem]').forEach(b=>b.addEventListener('click',()=>document.querySelector('#stem-output').textContent=t.items[Number(b.dataset.stem)][1]))};renderTool('evidence');
document.querySelectorAll('[data-tool]').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('[data-tool]').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderTool(b.dataset.tool)}));
const menu=document.querySelector('.menu-button'),nav=document.querySelector('.site-header nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));

