import {initializeApp} from "https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js";
import {getAuth,GoogleAuthProvider,onAuthStateChanged,signInWithPopup,signOut} from "https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js";
import {collection,doc,getDoc,getDocs,getFirestore,query,serverTimestamp,setDoc,where} from "https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js";
const config=window.BAKER_FIREBASE_CONFIG,status=document.querySelector('#teacher-status'),content=document.querySelector('#dashboard-content');let db,auth,rows=[];
const demoRows=[{date:new Date().toLocaleDateString('en-CA'),studentName:'Sample Student A',studentUid:'demo-a',period:3,standard:'ELA.6.R.2.4',label:'Argument',wordCount:72,confidence:3,prompt:'Should sixth-grade students have a short independent reading period every school day?',response:'Sixth-grade students should have independent reading time every day because it helps them discover books they enjoy and gives them regular practice. When students choose interesting books, they are more likely to keep reading. Daily practice can also help readers understand harder texts over time. A short reading period would make reading a normal part of the school day.'},{date:new Date().toLocaleDateString('en-CA'),studentName:'Sample Student B',studentUid:'demo-b',period:5,standard:'ELA.6.R.2.4',label:'Argument',wordCount:43,confidence:1,prompt:'Should sixth-grade students have a short independent reading period every school day?',response:'I think students should read every day because it can help them improve. It also gives people a quiet time to focus. Some students may find a book they really like. I still need help explaining my evidence more clearly.',editCount:1,editedAt:new Date()}];
document.querySelector('#date-filter').value=new Date().toLocaleDateString('en-CA');
if(!config?.projectId){document.querySelector('#teacher-signin').disabled=true;status.textContent='The secure account database has not been connected yet.'}
else{const app=initializeApp(config);auth=getAuth(app);db=getFirestore(app);const provider=new GoogleAuthProvider();document.querySelector('#teacher-signin').addEventListener('click',()=>signInWithPopup(auth,provider));document.querySelector('#teacher-signout').addEventListener('click',()=>signOut(auth));onAuthStateChanged(auth,async user=>{if(!user){content.hidden=true;document.querySelector('#auth-box').hidden=false;document.querySelector('#teacher-signout').hidden=true;return}const profile=await getDoc(doc(db,'users',user.uid));if(profile.data()?.role!=='teacher'){status.textContent='This account is not approved as a teacher account.';await signOut(auth);return}document.querySelector('#auth-box').hidden=true;document.querySelector('#teacher-signout').hidden=false;content.hidden=false;status.textContent=`Signed in as ${user.displayName||user.email}.`;loadToday();await loadData()})}
document.querySelector('#demo-dashboard').addEventListener('click',()=>{rows=[...demoRows];document.querySelector('#auth-box').hidden=true;content.hidden=false;populateFilters();render();status.textContent='Preview mode: these are sample submissions only. No student data is displayed.'});
async function loadData(){status.textContent='Loading submissions…';const date=document.querySelector('#date-filter').value;const snap=await getDocs(date?query(collection(db,'bellwork'),where('date','==',date)):collection(db,'bellwork'));rows=snap.docs.map(x=>({id:x.id,...x.data()}));populateFilters();render();status.textContent=`Loaded ${rows.length} submission${rows.length===1?'':'s'}.`}
function populateFilters(){const standardFilter=document.querySelector('#standard-filter'),standardValue=standardFilter.value;standardFilter.innerHTML='<option value="">All standards</option>'+[...new Set(rows.map(x=>x.standard).filter(Boolean))].sort().map(x=>`<option>${x}</option>`).join('');standardFilter.value=standardValue;const periodFilter=document.querySelector('#period-filter'),periodValue=periodFilter.value;periodFilter.innerHTML='<option value="">All periods</option>'+[...new Set(rows.map(x=>x.period).filter(Boolean))].sort((a,b)=>a-b).map(x=>`<option value="${x}">Period ${x}</option>`).join('');periodFilter.value=periodValue}
function filtered(){const s=document.querySelector('#standard-filter').value,p=document.querySelector('#period-filter').value;return rows.filter(x=>(!s||x.standard===s)&&(!p||String(x.period)===p))}
function render(){const data=filtered(),students=new Set(data.map(x=>x.studentUid));document.querySelector('#submission-total').textContent=data.length;document.querySelector('#student-total').textContent=students.size;document.querySelector('#word-average').textContent=data.length?Math.round(data.reduce((n,x)=>n+(x.wordCount||0),0)/data.length):0;document.querySelector('#help-total').textContent=data.filter(x=>x.confidence<=2).length;document.querySelector('#submission-list').innerHTML=data.length?data.sort((a,b)=>(a.studentName||'').localeCompare(b.studentName||'')).map((x,i)=>`<button class="submission-item${x.reviewedAt?' reviewed':''}" data-row="${i}"><b>${escapeHtml(x.studentName||'Student')}${x.editedAt?' <span class="edited-dot" title="Edited after first submitting">✏️</span>':''}${x.reviewedAt?' <span class="reviewed-dot" title="Checked in">✓</span>':''}</b><small>${x.period?`P${escapeHtml(x.period)} · `:''}${escapeHtml(x.standard||'')} · Confidence ${x.confidence||'—'}/4</small></button>`).join(''):'<p>No submissions match these filters.</p>';document.querySelectorAll('[data-row]').forEach(button=>button.addEventListener('click',()=>show(data[Number(button.dataset.row)])))}
function fmtTime(ts){try{const d=ts&&ts.toDate?ts.toDate():(ts?new Date(ts):null);return d?d.toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):''}catch(e){return ''}}
function show(x){const edited=x.editedAt?`<span class="edited-tag">Edited ${escapeHtml(fmtTime(x.editedAt))}</span>`:'';const period=x.period?`<span>Period ${escapeHtml(x.period)}</span>`:'';const review=x.reviewedAt?`<p class="reviewed-tag">✓ Checked in ${escapeHtml(fmtTime(x.reviewedAt))}</p>`:(x.id?'<button id="checkin-btn">Mark checked in</button>':'');document.querySelector('#response-detail').innerHTML=`<p class="eyebrow">${escapeHtml(x.date||'')}</p><h2>${escapeHtml(x.studentName||'Student')}</h2><div class="response-meta">${period}<span>${escapeHtml(x.standard||'')}</span><span>${x.wordCount||0} words</span><span>Confidence ${x.confidence||'—'}/4</span>${edited}</div><h3>${escapeHtml(x.prompt||'')}</h3><div class="response-copy">${escapeHtml(x.response||'')}</div>${review}`;const btn=document.querySelector('#checkin-btn');if(btn)btn.addEventListener('click',()=>checkIn(x))}
async function checkIn(x){if(!db||!x.id)return;try{await setDoc(doc(db,'bellwork',x.id),{reviewedAt:serverTimestamp(),reviewedBy:'teacher'},{merge:true});x.reviewedAt=new Date();render();show(x)}catch(e){status.textContent='Could not save the check-in. Try refreshing.'}}
async function loadToday(){if(!db)return;try{const snap=await getDoc(doc(db,'settings','today'));const s=snap.data()||{};const today=new Date().toLocaleDateString('en-CA');if(s.date===today){document.querySelector('#announce-input').value=s.announcement||'';document.querySelector('#prompt-input').value=s.prompt||'';document.querySelector('#starter-input').value=s.starter||''}}catch(e){}}
document.querySelector('#save-today').addEventListener('click',async()=>{const statusEl=document.querySelector('#today-status');if(!db){statusEl.textContent='Preview mode — sign in to publish.';return}try{await setDoc(doc(db,'settings','today'),{date:new Date().toLocaleDateString('en-CA'),announcement:document.querySelector('#announce-input').value.trim(),prompt:document.querySelector('#prompt-input').value.trim(),starter:document.querySelector('#starter-input').value.trim(),updatedAt:serverTimestamp()});statusEl.textContent='Published. Students will see it on their next page load.'}catch(e){statusEl.textContent='Publish failed — check that this account has the teacher role.'}});
function escapeHtml(value){const div=document.createElement('div');div.textContent=String(value);return div.innerHTML}
function exportCsv(){const data=filtered(),fields=['date','studentName','period','standard','label','wordCount','confidence','edited','response'],csv=[fields.join(','),...data.map(row=>fields.map(field=>{const v=field==='edited'?(row.editedAt?'edited':''):row[field];return `"${String(v??'').replaceAll('"','""')}"`}).join(','))].join('\n'),blob=new Blob([csv],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`bellwork-${document.querySelector('#date-filter').value||'all'}.csv`;a.click();URL.revokeObjectURL(a.href)}
document.querySelector('#refresh-data').addEventListener('click',loadData);document.querySelector('#export-data').addEventListener('click',exportCsv);document.querySelector('#standard-filter').addEventListener('change',render);document.querySelector('#period-filter').addEventListener('change',render);document.querySelector('#date-filter').addEventListener('change',loadData);
