import {initializeApp} from "https://www.gstatic.com/firebasejs/11.10.0/firebase-app.js";
import {getAuth,GoogleAuthProvider,onAuthStateChanged,signInWithPopup,signOut} from "https://www.gstatic.com/firebasejs/11.10.0/firebase-auth.js";
import {collection,doc,getDoc,getDocs,getFirestore,query,where} from "https://www.gstatic.com/firebasejs/11.10.0/firebase-firestore.js";
const config=window.BAKER_FIREBASE_CONFIG,status=document.querySelector('#teacher-status'),content=document.querySelector('#dashboard-content');let db,auth,rows=[];
const demoRows=[{date:new Date().toLocaleDateString('en-CA'),classCode:'PERIOD1',studentName:'Sample Student A',studentUid:'demo-a',standard:'ELA.6.R.2.4',label:'Argument',wordCount:72,confidence:3,prompt:'Should sixth-grade students have a short independent reading period every school day?',response:'Sixth-grade students should have independent reading time every day because it helps them discover books they enjoy and gives them regular practice. When students choose interesting books, they are more likely to keep reading. Daily practice can also help readers understand harder texts over time. A short reading period would make reading a normal part of the school day.'},{date:new Date().toLocaleDateString('en-CA'),classCode:'PERIOD2',studentName:'Sample Student B',studentUid:'demo-b',standard:'ELA.6.R.2.4',label:'Argument',wordCount:43,confidence:1,prompt:'Should sixth-grade students have a short independent reading period every school day?',response:'I think students should read every day because it can help them improve. It also gives people a quiet time to focus. Some students may find a book they really like. I still need help explaining my evidence more clearly.'}];
document.querySelector('#date-filter').value=new Date().toLocaleDateString('en-CA');
if(!config?.projectId){document.querySelector('#teacher-signin').disabled=true;status.textContent='The secure account database has not been connected yet.'}
else{const app=initializeApp(config);auth=getAuth(app);db=getFirestore(app);const provider=new GoogleAuthProvider();document.querySelector('#teacher-signin').addEventListener('click',()=>signInWithPopup(auth,provider));document.querySelector('#teacher-signout').addEventListener('click',()=>signOut(auth));onAuthStateChanged(auth,async user=>{if(!user){content.hidden=true;document.querySelector('#auth-box').hidden=false;document.querySelector('#teacher-signout').hidden=true;return}const profile=await getDoc(doc(db,'users',user.uid));if(profile.data()?.role!=='teacher'){status.textContent='This account is not approved as a teacher account.';await signOut(auth);return}document.querySelector('#auth-box').hidden=true;document.querySelector('#teacher-signout').hidden=false;content.hidden=false;status.textContent=`Signed in as ${user.displayName||user.email}.`;await loadData()})}
document.querySelector('#demo-dashboard').addEventListener('click',()=>{rows=[...demoRows];document.querySelector('#auth-box').hidden=true;content.hidden=false;populateFilters();render();status.textContent='Preview mode: these are sample submissions only. No student data is displayed.'});
async function loadData(){status.textContent='Loading submissions…';const date=document.querySelector('#date-filter').value;const snap=await getDocs(date?query(collection(db,'bellwork'),where('date','==',date)):collection(db,'bellwork'));rows=snap.docs.map(x=>({id:x.id,...x.data()}));populateFilters();render();status.textContent=`Loaded ${rows.length} submission${rows.length===1?'':'s'}.`}
function populateFilters(){const classFilter=document.querySelector('#class-filter'),standardFilter=document.querySelector('#standard-filter'),classValue=classFilter.value,standardValue=standardFilter.value;classFilter.innerHTML='<option value="">All classes</option>'+[...new Set(rows.map(x=>x.classCode).filter(Boolean))].sort().map(x=>`<option>${x}</option>`).join('');standardFilter.innerHTML='<option value="">All standards</option>'+[...new Set(rows.map(x=>x.standard).filter(Boolean))].sort().map(x=>`<option>${x}</option>`).join('');classFilter.value=classValue;standardFilter.value=standardValue}
function filtered(){const c=document.querySelector('#class-filter').value,s=document.querySelector('#standard-filter').value;return rows.filter(x=>(!c||x.classCode===c)&&(!s||x.standard===s))}
function render(){const data=filtered(),students=new Set(data.map(x=>x.studentUid));document.querySelector('#submission-total').textContent=data.length;document.querySelector('#student-total').textContent=students.size;document.querySelector('#word-average').textContent=data.length?Math.round(data.reduce((n,x)=>n+(x.wordCount||0),0)/data.length):0;document.querySelector('#help-total').textContent=data.filter(x=>x.confidence<=2).length;document.querySelector('#submission-list').innerHTML=data.length?data.sort((a,b)=>(a.studentName||'').localeCompare(b.studentName||'')).map((x,i)=>`<button class="submission-item" data-row="${i}"><b>${escapeHtml(x.studentName||'Student')}</b><small>${escapeHtml(x.classCode||'No class')} · ${escapeHtml(x.standard||'')} · Confidence ${x.confidence||'—'}/4</small></button>`).join(''):'<p>No submissions match these filters.</p>';document.querySelectorAll('[data-row]').forEach(button=>button.addEventListener('click',()=>show(data[Number(button.dataset.row)])))}
function show(x){document.querySelector('#response-detail').innerHTML=`<p class="eyebrow">${escapeHtml(x.date||'')} · ${escapeHtml(x.classCode||'')}</p><h2>${escapeHtml(x.studentName||'Student')}</h2><div class="response-meta"><span>${escapeHtml(x.standard||'')}</span><span>${x.wordCount||0} words</span><span>Confidence ${x.confidence||'—'}/4</span></div><h3>${escapeHtml(x.prompt||'')}</h3><div class="response-copy">${escapeHtml(x.response||'')}</div>`}
function escapeHtml(value){const div=document.createElement('div');div.textContent=String(value);return div.innerHTML}
function exportCsv(){const data=filtered(),fields=['date','classCode','studentName','standard','label','wordCount','confidence','response'],csv=[fields.join(','),...data.map(row=>fields.map(field=>`"${String(row[field]??'').replaceAll('"','""')}"`).join(','))].join('\n'),blob=new Blob([csv],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`bellwork-${document.querySelector('#date-filter').value||'all'}.csv`;a.click();URL.revokeObjectURL(a.href)}
document.querySelector('#refresh-data').addEventListener('click',loadData);document.querySelector('#export-data').addEventListener('click',exportCsv);document.querySelector('#class-filter').addEventListener('change',render);document.querySelector('#standard-filter').addEventListener('change',render);document.querySelector('#date-filter').addEventListener('change',loadData);
